name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./ci-node-app

      - name: Build
        run: npm run build
        working-directory: ./ci-node-app

      - name: Lint
        run: npm run lint
        working-directory: ./ci-node-app

      - name: Test
        run: npm run test
        working-directory: ./ci-node-app